<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1be168ccce420082b3e38eff9d672cef
{
    public static $prefixLengthsPsr4 = array (
        's' => 
        array (
            'setasign\\Fpdi\\' => 14,
            'setasign\\FpdiProtection\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'setasign\\Fpdi\\' => 
        array (
            0 => __DIR__ . '/..' . '/setasign/fpdi/src',
        ),
        'setasign\\FpdiProtection\\' => 
        array (
            0 => __DIR__ . '/..' . '/setasign/fpdi-protection/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FPDF' => __DIR__ . '/..' . '/setasign/fpdf/fpdf.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1be168ccce420082b3e38eff9d672cef::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1be168ccce420082b3e38eff9d672cef::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1be168ccce420082b3e38eff9d672cef::$classMap;

        }, null, ClassLoader::class);
    }
}
